"""Simplified Chinese (zh_CN) strings for the RLPE GUI.

Auto-generated from strings_en.py. Each key MUST exist in the
English STRINGS dict. Update via the /tmp/zh_translate.py build
script when the English dict changes.
"""

STRINGS = {
    'app.about.body': '<h3>RLPE - 放射虫图版提取系统</h3><p><b>版本：</b> {version}<br><b>作者：</b> {author}</p><p>基于 PySide6 + RLPE 流水线的原生 Qt6 桌面应用,配合 FastAPI 与 PBDB 数据库。</p>',
    'app.about.title': '关于 RLPE',
    'app.title': 'RLPE - 放射虫图版提取系统',
    'batch.add': '➕ 添加 PDF…',
    'batch.add_dir': '📁 添加目录…',
    'batch.browse': '浏览…',
    'batch.cancel': '取消',
    'batch.clear': '🗑 全部清空',
    'batch.count': '{n} 个 PDF 已入队',
    'batch.count.zero': '0 个 PDF 已入队',
    'batch.files': '📚 待处理 PDF (按串行顺序)',
    'batch.no_outdir.body': '请选择输出目录。',
    'batch.outdir.not_writable': '输出目录不可写。\n\n{path}\n\n{error}',
    'batch.no_outdir.title': '批处理',
    'batch.no_pdfs': '没有 PDF 已入队。',
    'batch.options': '⚙️ 批处理选项',
    'batch.outdir': '输出目录：',
    'batch.remove': '➖ 移除所选',
    'batch.start': '▶  开始批处理',
    'batch.stop_on_error': '首个错误即停止批处理',
    'batch.title': '批处理 — 队列多个 PDF',
    'batch.xlsx_at_end': '所有任务完成后导出合并 xlsx',
    'common.browse': '浏览…',
    # Phase 55 audit HIGH-7 fix: used as the directory-chooser dialog title
    # in settings_tab._pick_dir. Previously undefined → ⟦sentinel⟧.
    'common.choose_dir': '选择 {kind}',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.error': '错误',
    'common.info': '提示',
    'common.no': '否',
    'common.ok': '确定',
    'common.retry.body': '原文件已不存在:\n{path}',
    'common.retry.title': '重试',
    'common.save': '保存',
    'common.settings_saved': '设置已保存。',
    'common.warning': '警告',
    'common.yes': '是',
    'filter.all': '所有文件 (*)',
    'filter.csv': 'CSV 文件 (*.csv)',
    'filter.dir': '目录',
    'filter.json': 'JSON 文件 (*.json)',
    'filter.pdf': 'PDF 文件 (*.pdf)',
    'filter.xlsx': 'Excel 文件 (*.xlsx)',
    'filter.zip': 'Zip 文件 (*.zip)',
    'jobstab.clear_all': '全部清除',
    'jobstab.clear_finished': '清除已完成',
    'jobstab.col.elapsed': '耗时',
    'jobstab.col.id': '任务 ID',
    'jobstab.col.out': '输出',
    'jobstab.col.pdf': 'PDF',
    'jobstab.col.progress': '进度',
    'jobstab.col.rows': '行数',
    'jobstab.col.status': '状态',
    'jobstab.export.failed': '导出失败：{error}',
    'jobstab.export.no_rows': '没有可导出的行。',
    'jobstab.loaded_from_disk': '从磁盘加载',
    'jobstab.export.saved': '已保存 {count} 行 → {path}',
    'jobstab.export.saved_short': '已保存 → {path}',
    'jobstab.menu.export_json': '📤  导出 JSON',
    'jobstab.menu.export_xlsx': '📤  导出 xlsx',
    'jobstab.menu.open_out': '📁  打开输出目录',
    'jobstab.menu.open_results': '📊  在结果选项卡中打开',
    'jobstab.menu.remove': '🗑  从列表中移除',
    'jobstab.no_jobs': '0 个任务',
    'jobstab.status.cancelled': '已取消',
    'jobstab.status.done': '已完成',
    'jobstab.status.failed': '失败',
    'jobstab.status.queued': '排队中',
    'jobstab.status.running': '运行中',
    'main.batch_complete': '批处理完成。',
    'main.batch_stopped_on_error': '批处理因错误停止：{failed}（剩余 {remaining} 个）。',
    'main.done': '任务 {id} 完成 — {rows} 行',
    'main.failed': '任务 {id} 失败',
    'main.idle': '就绪',
    'main.recent_loaded': '已从磁盘加载 {n} 个历史任务。',
    'main.running': '任务 {id} 运行中…',
    'menu.file': '文件(&F)',
    'menu.file.batch': '📚  批处理…(&B)',
    'menu.file.open': '📂  打开 PDF…(&O)',
    'menu.file.outdir': '📁  打开输出目录…(&D)',
    'menu.file.quit': '退出(&Q)',
    'menu.help': '帮助(&H)',
    'menu.help.about': '关于 RLPE(&A)',
    'menu.theme': '🎨  主题(&T)',
    'menu.theme.dark': '深色(&D)',
    'menu.theme.light': '浅色(&L)',
    'menu.theme.system': '跟随系统(&S)',
    'menu.tools': '工具(&T)',
    'menu.tools.log': '📂  打开日志文件(&L)',
    'menu.view': '视图(&V)',
    'menu.view.jobs': '任务选项卡(&J)',
    'menu.view.results': '结果选项卡(&E)',
    'menu.view.run': '运行选项卡(&R)',
    'menu.view.settings': '设置选项卡(&S)',
    'preview.actual': '1:1',
    'preview.failed': '(加载失败) {name}',
    'preview.fit': '⛶',
    'preview.hint': '滚轮 = 缩放 · 拖拽 = 平移 · 双击 = 适合 · 点击 bbox 选中',
    'preview.missing': '(文件不存在) {name}',
    'preview.no_image': '(无图像)',
    'preview.zoom_in': '🔍+',
    'preview.zoom_out': '🔍−',
    'restab.col.biozone': '生物带',
    # Phase 55 audit fix: key renamed from caption_snip → caption_snippet
    # to match the pipeline's field name (constants.py:66).
    'restab.col.caption_snippet': 'Caption 摘要',
    'restab.col.confidence': '置信度',
    'restab.col.coord': '经纬度',
    'restab.col.country': '国家',
    'restab.col.family': 'PBDB 科',
    'restab.col.page_index': '页',
    'restab.col.panel_id': 'Panel ID',
    'restab.col.species': '物种 (拉丁名)',
    'restab.count': '{shown} / {total} 行',
    'restab.detail.bbox': 'Panel 边框',
    'restab.detail.caption': 'Caption',
    'restab.detail.class': '纲',
    'restab.detail.confidence': '置信度',
    'restab.detail.family': '科：{value}',
    'restab.detail.figure': '图',
    'restab.detail.geo_links': '地质链接 ({count})',
    'restab.detail.geo_links_more': '… 还有 {n} 条',
    'restab.detail.kingdom': '界',
    'restab.detail.order': '目',
    'restab.detail.page': '页',
    'restab.detail.paper': '论文',
    'restab.detail.paper_id': '论文ID',
    'restab.detail.figure_id': '图版ID',
    'restab.detail.panel_label': 'Panel标签',
    'restab.detail.geo_scope': '地质范围',
    'restab.detail.scope.panel': 'Panel专属',
    'restab.detail.scope.figure_anchor': '图级锚定',
    'restab.detail.scope.none': '无地质',
    'restab.detail.ocr.image_ocr': 'OCR',
    'restab.detail.ocr.positional': '位置',
    'restab.detail.ocr.no_image': '无图像',
    'restab.detail.pbdb_tax': 'PBDB 分类',
    'restab.detail.evidence': '提取证据',
    'restab.detail.phylum': '门',
    # Phase 64 Plan B (Task B.7): schematic figure content.
    'restab.detail.schematic': '示意图内容',
    'restab.detail.schematic_type': '图类型',
    'restab.detail.schematic_text_count': '文本元素',
    'restab.detail.schematic_rel_count': '关系数',
    'restab.detail.schematic_facts': '抽取的事实',
    'restab.detail.schematic_ages': '年代',
    'restab.detail.schematic_geo': '地名',
    'restab.detail.schematic_taxa': '分类',
    'restab.detail.schematic_confidence': '置信度',
    # Phase 65 Plan A.6: cross-figure linker source chip labels.
    'restab.detail.link_source.sample_match': '样品号匹配',
    'restab.detail.link_source.locality_match': '产地匹配',
    'restab.detail.link_source.m3_inference': 'M3 推理',
    'restab.detail.link_source.unlinked': '未关联',
    # Phase 66 Plan C.6: visual-coordinate cross-reference section
    # labels (Phase C fires only when Phase A Strategy-1 didn't match).
    'restab.detail.visual_links': '视觉坐标关联',
    'restab.detail.visual_target': '目标图',
    'restab.detail.visual_layer': '地层层位',
    'restab.detail.visual_age': '年代',
    'restab.detail.visual_formation': '组',
    'restab.detail.visual_confidence': '置信度',
    'restab.detail.visual_empty': '(无视觉关联)',
    'restab.detail.source': '来源',
    'restab.detail.title': '行详情',
    'restab.done': '任务 {id}  ·  {rows} 行',
    'restab.export.csv': '📤  导出 CSV',
    'restab.export.dwca': '📤  导出 DwCA',
    'restab.export.json': '📤  导出 JSON',
    'restab.export.xlsx': '📤  导出 xlsx',
    'restab.filter.all': '(全部)',
    'restab.filter.any': '(任意)',
    'restab.filter.family': 'PBDB 科：',
    'restab.filter.has_pbdb': '有 PBDB：',
    'restab.filter.no': '否',
    'restab.filter.species': '物种：',
    'restab.filter.yes': '是',
    'restab.live': '任务 {id}  ·  {rows} 行 (实时)',
    'restab.no_job': '未加载任务',
    'restab.search.label': '搜索：',
    'restab.search.placeholder': '按 species / caption / panel id / family 过滤…',
    'runtab.adv_group': '🔬 高级 (LLM / M3 / PBDB)',
    'runtab.basic_group': '⚙️ 基础配置',
    'runtab.browse': '浏览…',
    'runtab.cancel': '⏹  取消',
    'runtab.clear': '清除',
    'runtab.geo_vision': '多模态地质视觉',
    'runtab.gpu_check': '启动时自动检测 CUDA',
    'runtab.input.placeholder': '选择一篇放射虫论文 PDF 进行图版提取…',
    'runtab.input_group': '📄 输入 PDF',
    'runtab.label.caption_window': 'Caption 窗口 (GROBID)：',
    'runtab.label.dpi': '渲染 DPI：',
    'runtab.label.grobid_retries': 'GROBID 重试次数：',
    'runtab.label.grobid_timeout': 'GROBID 超时 (秒)：',
    'runtab.label.grobid_url': 'GROBID 地址：',
    'runtab.label.llm_backend': 'LLM 后端：',
    'runtab.label.m3_budget': 'M3 思考预算：',
    'runtab.label.m3_lang': 'M3 prompt 语言：',
    'runtab.label.m3_max_retries': 'M3 最大重试：',
    'runtab.label.m3_model': 'M3 模型：',
    'runtab.label.m3_output': 'M3 最大输出 tokens：',
    'runtab.label.m3_timeout': 'M3 超时 (秒)：',
    'runtab.label.ocr_backend': 'OCR 后端：',
    'runtab.label.ocr_lang': 'OCR 语言：',
    'runtab.label.od_caption_window': 'OD Caption 窗口：',
    'runtab.label.paleodb_occ': 'PBDB 最大 occurrence 数：',
    'runtab.label.panel_score': 'Panel 分数阈值：',
    'runtab.label.use_gpu': '使用 GPU：',
    'runtab.label.workers': '工作线程数：',
    'runtab.m3_multi_plate': 'M3 多图版增强',
    'runtab.m3_stage3': 'M3 阶段 3 (panel 精修)',
    'runtab.ocr_lang.placeholder': '如 English、中文 (简体)、日本語',
    'runtab.ocr_lang.tooltip': 'OCR 语言（如 English、中文、日本語）。\n可编辑——高级用户可输入 "en,ja" 以支持多语言。',
    'runtab.od_fallback': 'GROBID 失败时允许 OpenDataLoader 兜底',
    'runtab.out.choose': '选择…',
    'runtab.out.open': '打开',
    'runtab.out.placeholder': 'manifest / figures / xlsx 等输出文件的保存位置…',
    'runtab.out_group': '💾 输出目录',
    'runtab.progress.done': '流水线已完成。结果请见结果选项卡。',
    'runtab.progress.idle': '空闲  (%v / %m)',
    'runtab.progress.init': '流水线初始化中…',
    'runtab.progress.starting': '启动中…',
    'runtab.progress.working': '处理中…',
    'runtab.prompt.cancelled': '已请求取消。',
    'runtab.prompt.error.title': '流水线错误',
    'runtab.prompt.no_outdir.body': '请先选择输出目录。',
    'runtab.prompt.no_outdir.title': '未选择输出目录',
    'runtab.prompt.no_pdf.body': '请先选择一个有效的 PDF 文件。',
    'runtab.prompt.no_pdf.title': '未选择 PDF',
    'runtab.save_intermediate': '保存中间 panel (占用大量磁盘)',
    'runtab.start': '▶  开始提取',
    'runtab.status.cancelling': '取消中…',
    'runtab.status.done': '完成',
    'runtab.status.failed': '失败',
    'runtab.status.idle': '空闲',
    'runtab.status.running': '运行中',
    'runtab.status.starting': '启动中…',
    'runtab.use_pbdb': '使用 PBDB (古生物数据库) 补充分类与 occurrence 信息',
    'settab.appearance': '外观',
    'settab.diag': '诊断',
    'settab.diag.dpi': '渲染 DPI：',
    'settab.diag.log_btn': '📂 打开日志文件',
    'settab.diag.log_label': '日志：',
    'settab.diag.save_intermediate': '保存中间 panel (占用大量磁盘)',
    'settab.dir.out': '默认输出目录：',
    'settab.dir.pdf': '默认 PDF 目录：',
    'settab.dirs': '默认目录',
    'settab.grobid': 'GROBID',
    'settab.grobid.retries': '最大重试：',
    'settab.grobid.timeout': '超时 (秒)：',
    'settab.grobid.url': 'GROBID 地址：',
    'settab.llm': 'LLM / M3',
    'settab.llm.backend': 'LLM 后端：',
    'settab.log.open_fail': '无法打开：{error}\n\n路径：{path}',
    'settab.log.path': '日志文件：{path}',
    'settab.log.not_yet': '暂无日志文件。\n\n日志将在首次运行流水线后生成。\n\n预期路径：\n{path}',
    'settab.log.title': '日志文件',
    'settab.m3.budget': 'M3 思考预算：',
    'settab.m3.lang': 'M3 prompt 语言：',
    'settab.m3.max_retries': 'M3 最大重试：',
    'settab.m3.model': 'M3 模型：',
    'settab.m3.output': 'M3 最大输出 tokens：',
    'settab.m3.timeout': 'M3 超时 (秒)：',
    'settab.ocr': 'OCR',
    'settab.ocr.backend': 'OCR 后端：',
    'settab.ocr.caption_window': 'Caption 窗口 (GROBID)：',
    'settab.ocr.lang': 'OCR 语言：',
    'settab.ocr.lang.placeholder': 'English、中文 (简体)、日本語…',
    'settab.ocr.od_caption_window': 'OD Caption 窗口：',
    'settab.pbdb': 'PBDB',
    'settab.pbdb.endpoint': 'PBDB 端点：',
    'settab.pbdb.endpoint.placeholder': '(留空使用默认值)',
    'settab.pbdb.occ': '每个 species 最大 occurrence 数：',
    'settab.pbdb.use': '启用 PBDB 补充 (分类 + occurrence)',
    'settab.reset': '恢复默认',
    'settab.reset.confirm.body': '这将把所有设置恢复为默认值。继续？',
    'settab.reset.confirm.title': '恢复默认设置？',
    'settab.reset.done': '已恢复默认设置。',
    'settab.save': '💾 保存设置',
    'settab.save.done': '设置已保存。',
    'settab.theme': '主题：',
    'settab.title': '⚙️ {app}  ·  v{version}',
    'settab.yolo': 'YOLO 放射虫检测',
    'settab.yolo.enable': '启用 YOLO 检测 (替代 OpenCV)',
    'settab.yolo.model_path': '模型路径：',
    'settab.yolo.conf': '置信度阈值：',
    'settab.yolo.iou': 'NMS IoU 阈值：',
    'settab.yolo.browse': '浏览…',
    'tab.jobs': '📋  任务',
    'tab.results': '📊  结果',
    'tab.run': '▶  运行',
    'tab.settings': '⚙️  设置',
    'toolbar.about': 'ℹ️  关于',
    'toolbar.batch': '📚  批处理…',
    'toolbar.jobs': '📋  任务',
    'toolbar.open': '📂  打开 PDF',
    'toolbar.results': '📊  结果',
    'toolbar.run': '▶  运行',
    'toolbar.settings': '⚙️  设置',
    'toolbar.title': '主工具栏',
    # Added in Phase 34 for language switcher
    'settab.lang': '语言：',
    'app.name': 'RLPE - 放射虫图版提取系统',
    'app.version': '0.1.0',
    # ============================================================
    # Phase 48: file-dialog titles + export dialogs + summary labels
    # ============================================================
    # Run tab file dialogs
    'runtab.browse.title': '选择放射虫论文 PDF',
    'runtab.out.choose.title': '选择输出目录',
    'runtab.out.no_outdir.title': '输出目录',
    'runtab.out.no_outdir.body': '尚未选择输出目录。',
    # Batch dialog file dialogs
    'batch.add.title': '添加 PDF',
    'batch.add_dir.title': '选择 PDF 所在目录',
    'batch.outdir.title': '选择批处理输出目录',
    # Jobs tab exports
    'jobstab.export.xlsx_title': '导出 xlsx',
    'jobstab.export.json_title': '导出 JSON',
    # Results tab exports
    'restab.export.xlsx_title': '导出 xlsx',
    'restab.export.json_title': '导出 JSON',
    'restab.export.csv_title': '导出 CSV',
    'restab.export.dwca_title': '导出 DwCA',
    # Jobs tab summary
    'jobstab.summary.count': '{total} 个任务 · 运行中 {running} · 已完成 {done} · 失败 {failed}',
    'jobstab.summary.count_label': '{total} 个任务  ·  运行中 {running}  ·  已完成 {done}  ·  失败 {failed}',
}


# Phase 55 audit M3 — fail loudly if the auto-translate script ever
# emits a duplicate key. Python silently keeps the LAST duplicate
# in a dict literal, masking upstream bugs in the translation
# generator. Walking ``STRINGS.items()`` and reporting collisions
# here surfaces them at import time (which runs at GUI startup)
# instead of letting them silently shadow each other.
# Phase 55 audit M3 — fail loudly if the auto-translate script ever
# emits a duplicate key. Python silently keeps the LAST duplicate
# in a dict literal, masking upstream bugs in the translation
# generator. We re-parse the source file (this very module) and
# count key occurrences, since ``dict[key]`` after a duplicate
# only sees the last value and gives no signal.
import re as _re_dup
_src_dup = _re_dup.sub(r"\"\"\".*?\"\"\"", "", open(__file__, encoding="utf-8").read(), flags=_re_dup.S)
_keys_dup = _re_dup.findall(r"^\s*['\"]([a-zA-Z][\w.]*)['\"]\s*:", _src_dup, flags=_re_dup.M)
import collections as _coll_dup
_dup_counts = _coll_dup.Counter(_keys_dup)
_dup_check = [k for k, n in _dup_counts.items() if n > 1]
if _dup_check:
    raise RuntimeError(
        f"strings_zh_CN has duplicate keys: {_dup_check!r}. "
        "Re-run /tmp/zh_translate.py after fixing the upstream "
        "generator (each English key MUST map to exactly one "
        "Chinese translation)."
    )
del _dup_check, _dup_counts, _keys_dup, _src_dup
