"""v17 → v18: re-assign panel_id using OCR'd label from each panel image.

The v17 predictions were generated by a pipeline run where the
corner-OCR band was too small to read labels in bandini2011 / other
papers. As a result, 100% of v17 panel_id values fell back to the
caption label list (positional), making pred_id = caption_label[i] but
the IMAGE at panel_NN.png shows a different label (the actual visible
label in the cropped image). Eval F1 was 98.19% but visually the
predictions were wrong.

This script:
  1. Loads the v17 predictions
  2. For each row with a panel_path, OCRs the image to find the
     visible label
  3. Updates the row's panel_id to the OCR'd label
  4. Looks up the species in (parsed_caption, panel_id) for the
     updated panel_id — so the species string follows the
     visible label
  5. Writes v18 predictions

Effect: pred panel_id now matches the actual visible label in
the panel image. Eval F1 will be the *real* F1 (likely lower
than 98.19% but accurate).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
sys.path.insert(0, str(SRC))

import easyocr  # noqa: E402
import numpy as np  # noqa: E402
from PIL import Image  # noqa: E402

from rlpe.m3_engine import _regex_parse_caption  # noqa: E402
from rlpe.opendataloader_extractor import _find_plate_captions  # noqa: E402

PRED_IN = ROOT / "work" / "combined_9_v17_FINAL.jsonl"
PRED_OUT = ROOT / "work" / "combined_9_v18_FINAL.jsonl"

# Same OD JSON paths as refresh_all_predictions.py
OD_JSON_BY_PAPER = {
    "4f1bf415485765b8": ROOT
    / "work"
    / "all7_rerun"
    / "output"
    / "od_output"
    / "4f1bf415485765b8"
    / "bandini2011.json",
    "58d7972c37307959": ROOT
    / "work"
    / "all7_rerun"
    / "output"
    / "od_output"
    / "58d7972c37307959"
    / "baumgartner2008.json",
    "178d4e1e9d93136c": ROOT
    / "work"
    / "boughdiri_rerun"
    / "output"
    / "od_output"
    / "178d4e1e9d93136c"
    / "boughdiri2007.json",
    "17a129b4e9ca975a": ROOT
    / "work"
    / "all7_rerun"
    / "output"
    / "od_output"
    / "17a129b4e9ca975a"
    / "danelian2006.json",
    "e28de2b07edc8950": ROOT
    / "work"
    / "feng_rerun_v2"
    / "output"
    / "od_output"
    / "e28de2b07edc8950"
    / "feng2007.json",
    "a0f363c21b6941d7": ROOT
    / "work"
    / "all7_rerun"
    / "output"
    / "od_output"
    / "a0f363c21b6941d7"
    / "hollis2006.json",
    "2225994d55021328": next(
        (ROOT / "work" / "pouille_recon" / "od_output" / "4dc5b4d95e910e95").glob("*.json")
    ),
    "5d5264c7bf0b0a43": ROOT
    / "work"
    / "beccaro_only_out"
    / "output"
    / "od_output"
    / "5d5264c7bf0b0a43"
    / "beccaro2006.json",
    "2e85364a3c605326": ROOT
    / "work"
    / "bragin_only_out"
    / "output"
    / "od_output"
    / "2e85364a3c605326"
    / "bragin2025.json",
}


def _build_label_to_species_for(paper_id: str) -> dict[str, dict[str, str]]:
    od_path = OD_JSON_BY_PAPER[paper_id]
    if not od_path.exists():
        return {}
    with open(od_path) as f:
        doc = json.load(f)
    captions = _find_plate_captions(doc.get("kids", []))
    out: dict[str, dict[str, str]] = {}
    for c in captions:
        if c.get("kind") == "fig":
            continue
        plate = str(c["plate_number"])
        pairs = _regex_parse_caption(c["content"])
        bucket = out.setdefault(plate, {})
        for p in pairs:
            sp = p.species.strip()
            mod = (p.modifier or "").strip()
            if mod:
                sp = (sp + " " + mod).strip()
            for lbl in p.labels:
                bucket.setdefault(lbl, sp)
    return out


def _plate_from_figure_id(figure_id: str) -> str | None:
    if not figure_id or "_pl0" not in figure_id:
        return None
    return figure_id.rsplit("_pl0", 1)[-1]


def _resolve_panel_path(panel_path: str) -> Path | None:
    """Resolve a panel image path. The v17 predictions were written for
    a specific run directory layout; the files may have moved. Search
    by the unique (paper_id, figure_id, panel_NN.png) tail under any
    work/*/panels/<paper_id>/ directory."""
    if panel_path and Path(panel_path).exists():
        return Path(panel_path)
    # Tail = .../<paper_id>/<fig>/panel_NN.png
    parts = Path(panel_path).parts
    # Find the last path component that matches "panel_NN.png"
    if not parts or "panel_" not in parts[-1]:
        return None
    tail = Path(*parts[-3:])  # paper_id / figure / panel_NN.png
    candidates = list(
        ROOT.glob(f"work/*/panels/{tail.parent.parent.name}/{tail.parent.name}/{tail.name}")
    )
    if not candidates:
        # Try a more relaxed search: match by paper_id only
        candidates = list(ROOT.glob(f"work/*/panels/{tail.parent.parent.name}/**/{tail.name}"))
    if candidates:
        return candidates[0]
    return None


def _ocr_panel_label(reader, image_path: Path) -> list[str]:
    """OCR a panel image, return all numeric tokens."""
    if not image_path.exists():
        return []
    arr = np.array(Image.open(image_path).convert("RGB"))
    tokens = reader.readtext(arr)
    nums = []
    for t in tokens:
        m = re.fullmatch(r"\d{1,3}", t[1].strip())
        if m:
            nums.append(t[1].strip())
    return nums


def main() -> int:
    # Build label→species map per paper
    paper_to_mapping: dict[str, dict[str, dict[str, str]]] = {}
    for pid in OD_JSON_BY_PAPER:
        paper_to_mapping[pid] = _build_label_to_species_for(pid)
        n_pairs = sum(len(d) for d in paper_to_mapping[pid].values())
        print(f"{pid}: {n_pairs} (plate, label) → species entries")

    # Init EasyOCR
    print("\nLoading EasyOCR...")
    reader = easyocr.Reader(["en"], gpu=False)
    print("EasyOCR loaded\n")

    rows = [json.loads(l) for l in PRED_IN.read_text().splitlines() if l]
    print(f"Loaded {len(rows)} predictions from {PRED_IN.name}")

    reassigned = 0
    unchanged = 0
    ocr_failed = 0
    new_out: list[dict] = []
    for r in rows:
        pid = r.get("paper_id")
        plate = _plate_from_figure_id(r.get("figure_id", ""))
        panel_id_old = r.get("panel_id", "")
        panel_path = r.get("panel_path", "")
        if not (pid and plate and panel_path):
            new_out.append(r)
            ocr_failed += 1
            continue
        resolved = _resolve_panel_path(panel_path)
        if resolved is None:
            new_out.append(r)
            ocr_failed += 1
            continue
        # OCR the panel image
        nums = _ocr_panel_label(reader, resolved)
        if not nums:
            new_out.append(r)
            ocr_failed += 1
            continue
        # Take the FIRST numeric token (most prominent label)
        new_panel_id = nums[0]
        if new_panel_id != panel_id_old:
            reassigned += 1
        else:
            unchanged += 1
        # Look up species for new panel_id
        new_species = paper_to_mapping.get(pid, {}).get(plate, {}).get(new_panel_id)
        r2 = dict(r)
        r2["panel_id"] = new_panel_id
        r2["metadata"] = dict(r.get("metadata") or {})
        r2["metadata"]["v18_panel_id_source"] = "image_ocr"
        r2["metadata"]["v18_old_panel_id"] = panel_id_old
        if new_species is not None:
            r2["species"] = new_species
        new_out.append(r2)

    PRED_OUT.write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in new_out) + "\n")
    print(f"\nWrote {len(new_out)} rows to {PRED_OUT.name}")
    print(f"  Reassigned: {reassigned}")
    print(f"  Unchanged: {unchanged}")
    print(f"  OCR failed / no path: {ocr_failed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
