"""Pydantic v2 schema models for the published RLPE output contract.

These models define the *exported* record shape. Internal pipeline code
keeps the existing dataclass types in ``types.py`` (no breaking change
to consumers). At export time, internal ``MatchResult`` is converted to
a :class:`PanelRecord` for JSON Schema validation and downstream use.

Three views are produced by transforming :class:`PanelRecord`:
    - analysis: CSV/Parquet with DwC field names (for paleontologists)
    - ml: JSONL with train/val/test split (for ML researchers)
    - archive: DwC-A zip (for PBDB/GBIF ingest)

The JSON Schema is generated by :func:`emit_json_schema` and published
to ``schemas/rlpe-v1.0.0.json``. Increment ``SCHEMA_VERSION`` whenever
a field is added, removed, or has its semantics changed.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

SCHEMA_VERSION = "1.0.0"

# Strict mode for exported records. ``extra="forbid"`` means a JSONL
# record with an unknown field is rejected, which protects downstream
# consumers from typos in upstream code.
StrictModel = ConfigDict(
    extra="forbid",
    populate_by_name=True,
    str_strip_whitespace=False,  # preserve raw panel labels like "0" vs " 0"
)


class ScaleBarRecord(BaseModel):
    """A scale-bar measurement attached to a panel/figure."""

    model_config = StrictModel
    value: float | None = None
    unit: str | None = None
    source: str | None = None  # "caption" | "ocr" | "image"
    pixel_length: float | None = None
    um_per_px: float | None = None
    confidence: float = 0.0


class GeologyLinkRecord(BaseModel):
    """A geology-fact link associated with a panel's caption context."""

    model_config = StrictModel
    age: str | None = None
    chronostratigraphy: str | None = None
    chronostratigraphy_rank: str | None = None
    formation: str | None = None
    locality: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    section_type: str | None = None
    section_title: str | None = None
    evidence_text: str | None = None
    confidence: float = 0.0


class PaperMetadataRecord(BaseModel):
    """Bibliographic metadata for the source paper."""

    model_config = StrictModel
    title: str | None = None
    authors: list[str] = Field(default_factory=list)
    year: int | None = None
    journal: str | None = None
    volume: str | None = None
    issue: str | None = None
    pages: str | None = None
    doi: str | None = None
    abstract: str | None = None
    keywords: list[str] = Field(default_factory=list)
    publisher: str | None = None
    page_count: int | None = None
    source: str = ""  # "grobid" | "opendataloader" | "none"
    confidence: float = 0.0


class ProvenanceRecord(BaseModel):
    """Provenance metadata stamped onto every exported run."""

    model_config = StrictModel
    pipeline_version: str
    schema_version: str
    git_commit: str
    git_dirty: bool
    config_snapshot: dict[str, Any] = Field(default_factory=dict)
    input_sha256: dict[str, str] = Field(default_factory=dict)
    timestamp_utc: str
    host: str
    python_version: str


class PanelMetadata(BaseModel):
    """Per-panel diagnostic metadata (no business data here)."""

    model_config = StrictModel
    panel_score: float | None = None
    ocr_count: int = 0
    taxon_count: int = 0
    figure_number: str | None = None
    page_index: int | None = None
    matcher_used: bool = False
    matcher_type: str = "heuristic"
    matcher_conf: float = 0.0
    caption_pairs_used: bool = False
    scale_bar: ScaleBarRecord | None = None
    geology_links: list[GeologyLinkRecord] = Field(default_factory=list)
    m3_diagnostic: dict[str, Any] = Field(default_factory=dict)
    extraction_source: str = ""
    reassigned_from_figure: str | None = None
    reassigned_reason: str | None = None


class PanelRecord(BaseModel):
    """A single panel in a single figure of a single paper.

    This is the canonical record published as JSONL. Each downstream view
    (analysis/ML/archive) is a projection of this record.
    """

    model_config = StrictModel
    paper_id: str
    figure_id: str
    panel_id: str | None
    species: str | None
    panel_path: str | None
    bbox: list[int] | None = Field(default=None, min_length=4, max_length=4)
    confidence: float
    label_text: str | None = None
    caption_snippet: str | None = None
    ocr_text: str | None = None
    metadata: PanelMetadata = Field(default_factory=PanelMetadata)
    paper_metadata: PaperMetadataRecord | None = None


class RunOutput(BaseModel):
    """The top-level shape of an exported run.

    The provenance block is mandatory and is validated separately so a
    run without provenance cannot be exported.
    """

    model_config = StrictModel
    schema_version: str = SCHEMA_VERSION
    provenance: ProvenanceRecord
    panels: list[PanelRecord] = Field(default_factory=list)


def emit_json_schema(target: Path) -> Path:
    """Write the canonical JSON Schema for ``RunOutput`` to ``target``.

    Idempotent: running twice with the same target produces the same file.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    schema = RunOutput.model_json_schema()
    schema["$id"] = f"https://rlpe.local/schemas/rlpe-v{SCHEMA_VERSION}.json"
    schema["title"] = "RLPE RunOutput"
    schema["description"] = (
        "Canonical export shape of a Radiolarian Literature Plate Extractor "
        "run. Each RunOutput carries a ProvenanceRecord and a list of "
        "PanelRecord entries. Downstream views (analysis/ML/archive) are "
        "projections of this shape."
    )
    with open(target, "w", encoding="utf-8") as f:
        json.dump(schema, f, indent=2, sort_keys=True, ensure_ascii=False)
    return target


def validate_run_output(payload: dict[str, Any]) -> RunOutput:
    """Validate a parsed JSON payload against the published schema.

    Raises ``pydantic.ValidationError`` on any mismatch. Returns the
    typed :class:`RunOutput` for downstream use.
    """
    return RunOutput.model_validate(payload)
