"""Pydantic v2 schema models for the published RLPE output contract.

These models define the *exported* record shape. Internal pipeline code
keeps the existing dataclass types in ``types.py`` (no breaking change
to consumers). At export time, internal ``MatchResult`` is converted to
a :class:`PanelRecord` for JSON Schema validation and downstream use.

Three views are produced by transforming :class:`PanelRecord`:
    - analysis: CSV/Parquet with DwC field names (for paleontologists)
    - ml: JSONL with train/val/test split (for ML researchers)
    - archive: DwC-A zip (for PBDB/GBIF ingest)

The JSON Schema is generated by :func:`emit_json_schema` and published
to ``schemas/rlpe-v{SCHEMA_VERSION}.json``. Increment ``SCHEMA_VERSION``
whenever a field is added, removed, or has its semantics changed.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

SCHEMA_VERSION = "1.2.0"

# Strict mode for exported records. ``extra="forbid"`` means a JSONL
# record with an unknown field is rejected, which protects downstream
# consumers from typos in upstream code.
StrictModel = ConfigDict(
    extra="forbid",
    populate_by_name=True,
    str_strip_whitespace=False,  # preserve raw panel labels like "0" vs " 0"
)


class ScaleBarRecord(BaseModel):
    """A scale-bar measurement attached to a panel/figure."""

    model_config = StrictModel
    value: float | None = None
    unit: str | None = None
    source: str | None = None  # "caption" | "ocr" | "image"
    pixel_length: float | None = None
    um_per_px: float | None = None
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    # Phase 61 Plan 4.6 (Bug 4.6): scale_bar sanity check flags
    # 2x-10x disagreement ("scale_bar_disagreement") or drops value on
    # >10x disagreement (value=None, warning="scale_bar_10x_disagreement").
    warning: str | None = None


class GeologyLinkRecord(BaseModel):
    """A geology-fact link associated with a panel's caption context."""

    model_config = StrictModel
    age: str | None = None
    chronostratigraphy: str | None = None
    chronostratigraphy_rank: str | None = None
    # Numeric age interval in Ma, when the chronostratigraphic term can
    # be mapped to an ICS interval. Optional so legacy records remain
    # valid; first-stage exporters may leave these empty.
    ma_top: float | None = None
    ma_base: float | None = None
    ma_mid: float | None = None
    formation: str | None = None
    member: str | None = None
    group: str | None = None
    lithology: str | None = None
    locality: str | None = None
    country: str | None = None
    latitude: float | None = Field(default=None, ge=-90.0, le=90.0)
    longitude: float | None = Field(default=None, ge=-180.0, le=180.0)
    modern_latitude: float | None = Field(default=None, ge=-90.0, le=90.0)
    modern_longitude: float | None = Field(default=None, ge=-180.0, le=180.0)
    paleo_latitude: float | None = Field(default=None, ge=-90.0, le=90.0)
    paleo_longitude: float | None = Field(default=None, ge=-180.0, le=180.0)
    plate_id: str | None = None
    reconstruction_model: str | None = None
    reconstruction_age_ma: float | None = None
    sample_id: str | None = None
    section_type: str | None = None
    section_title: str | None = None
    evidence_text: str | None = None
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    biozone: str | None = None  # optional biozone name (e.g. "N. optima Zone")
    # Phase 63 Plan 6.15 (Bug 6.15): GBIF requires
    # ``coordinateUncertaintyInMeters`` on georeferenced occurrences.
    # Derived from ``coord_source``: regex-extracted -> 1000m, modern
    # centroid -> 25000m, paleodb-derived -> 5000m. ``None`` means
    # the coordinate is missing / not provided.
    coordinate_uncertainty_in_meters: float | None = None
    # Phase 65 / audit 2026-07-24 (P1-1): track the cross-figure
    # link provenance so a Darwin Core / GBIF auditor can trace
    # each link back to its source figure. ``link_source`` is
    # one of ``"sample_match" | "locality_match" | "m3_inference"
    # | "unlinked"``. ``figure_id`` is the source figure's id
    # (None for unlinked fallbacks). Required for Phase A's
    # provenance contract — downstream consumers can't tell
    # whether a panel's age came from Figure 3 (strat column)
    # or Figure 7 (paleogeographic map) without these.
    figure_id: str | None = None
    link_source: str | None = None
    # Round 24: environment / geochem / facies fields. The
    # radiolarian-extraction user requested these to support
    # Permian–Triassic extinction / recovery studies (P/T
    # boundary, anoxic events, etc.) where the core research
    # question is "when did radiolarians go extinct due to
    # anoxia / acidification / cooling, and when did they
    # recover?". Without these proxies, the data is not
    # geochemically contextualised.
    #
    # Each field is a single keyword from a curated vocabulary
    # (see ``geology_extraction._PALEOENVIRONMENT_VOCAB`` etc.).
    # Round 24 dictionaries are English; the extractor matches
    # case-insensitive. The ``evidence_*`` fields carry the
    # sentence the term was extracted from so the operator can
    # verify the source.
    paleoenvironment: str | None = None  # e.g. "anoxic", "oxic", "upwelling"
    redox: str | None = None  # e.g. "euxinic", "dysoxic", "oxic" (per Algeo & Tribovillard 2009)
    chemostrat: str | None = None  # e.g. "δ13C excursion", "CIE", "TE disaster"
    facies: str | None = None  # e.g. "pelagic", "turbidite", "platform", "basin"
    # Round 22 audit: how the coordinates were derived. Empty string
    # for regex-extracted coords (the default path), ``"country_centroid"``
    # when the Round 21 country-centroid fallback supplied the lat/lon.
    # The frontend / downstream consumers can use this to badge
    # centroid-derived coords.
    coord_source: str = ""


class PaperMetadataRecord(BaseModel):
    """Bibliographic metadata for the source paper."""

    model_config = StrictModel
    title: str | None = None
    authors: list[str] = Field(default_factory=list)
    year: int | None = None
    journal: str | None = None
    volume: str | None = None
    issue: str | None = None
    pages: str | None = None
    doi: str | None = None
    abstract: str | None = None
    keywords: list[str] = Field(default_factory=list)
    publisher: str | None = None
    page_count: int | None = None
    source: str = ""  # "grobid" | "opendataloader" | "none"
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)


class ProvenanceRecord(BaseModel):
    """Provenance metadata stamped onto every exported run."""

    model_config = StrictModel
    pipeline_version: str
    schema_version: str
    git_commit: str
    git_dirty: bool
    config_snapshot: dict[str, Any] = Field(default_factory=dict)
    input_sha256: dict[str, str] = Field(default_factory=dict)
    timestamp_utc: str
    host: str
    python_version: str


class PaperRecord(BaseModel):
    """One source paper in an RLPE run.

    This is the paper-level view of :class:`PaperMetadataRecord`. It is
    optional and additive: legacy RunOutput payloads without ``papers``
    remain valid.
    """

    model_config = StrictModel
    paper_id: str
    title: str | None = None
    authors: list[str] = Field(default_factory=list)
    year: int | None = None
    journal: str | None = None
    volume: str | None = None
    issue: str | None = None
    pages: str | None = None
    doi: str | None = None
    abstract: str | None = None
    keywords: list[str] = Field(default_factory=list)
    publisher: str | None = None
    page_count: int | None = None
    # P3-3 fix: docstring noting these fields are not yet populated.
    # Wiring requires passing PDF path from PipelineConfig through
    # MatchResult → PaperMetadata → PaperRecord. Consumers should
    # not rely on these fields until that chain is implemented.
    source_pdf: str | None = None
    pdf_sha256: str | None = None
    source: str = ""
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    # Round 22 audit: ``paper_records_from_matches`` previously
    # injected ``review_reasons`` and ``needs_review`` into the
    # dumped dict AFTER validation, but those keys were never
    # declared on the model, so they bypassed the strict schema
    # silently. We now declare them so the Round 20 cleanup's
    # ``title_extraction_failed`` / ``authors_input2`` flags
    # actually reach the frontend.
    review_reasons: list[str] = Field(default_factory=list)
    needs_review: bool = False


class ReviewFlagRecord(BaseModel):
    """Human-review state for one extracted entity."""

    model_config = StrictModel
    entity_type: str
    entity_id: str
    needs_review: bool = False
    review_reasons: list[str] = Field(default_factory=list)
    reviewer_status: str | None = None


class FigureRecord(BaseModel):
    """A figure/plate/map/range-chart detected in a paper."""

    model_config = StrictModel
    figure_id: str
    paper_id: str
    figure_number: str | None = None
    figure_type: str | None = None  # "plate" | "map" | "range_chart" | "photo" | ...
    page_index: int | None = None
    caption: str | None = None
    caption_source: str | None = None
    image_path: str | None = None
    bbox: list[int] | None = Field(default=None, min_length=4, max_length=4)

    # Audit 2026-09-01 CR-12: enforce non-negative, non-zero bbox.
    # The previous schema accepted ``[-5, -5, 0, 0]`` — negative
    # coordinates AND a zero-area dimension. Downstream
    # export / GBIF submit rejected these silently (the row was
    # just dropped), inflating the false-negative rate. Now we
    # reject any bbox with ``min < 0`` or ``max == min`` (zero
    # width OR zero height — a true 0×0 panel is always a
    # detector mis-fire, never a real specimen).
    @field_validator("bbox")
    @classmethod
    def _validate_bbox(cls, v: list[int] | None) -> list[int] | None:
        if v is None:
            return v
        if len(v) != 4:
            raise ValueError(
                f"bbox must be exactly 4 ints [x, y, w, h] or [x1, y1, x2, y2]; got {v!r}"
            )
        if any(int(x) < 0 for x in v):
            raise ValueError(f"bbox must not contain negative coordinates; got {v!r}")
        if v[2] <= 0 or v[3] <= 0:
            # Treat ``[x, y, w, h]`` form (zero width/height) and
            # ``[x1, y1, x2, y2]`` form (x2 <= x1) uniformly.
            raise ValueError(f"bbox must have positive width AND height (or x2 > x1); got {v!r}")
        return [int(x) for x in v]

    scale_bar: ScaleBarRecord | None = None
    panel_ids: list[str] = Field(default_factory=list)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    needs_review: bool = False
    review_reasons: list[str] = Field(default_factory=list)


class TaxonRecord(BaseModel):
    """Structured taxonomic name extracted for one or more panels."""

    model_config = StrictModel
    taxon_id: str
    verbatim_name: str | None = None
    normalized_name: str | None = None
    genus: str | None = None
    specific_epithet: str | None = None
    qualifier: str | None = None  # "cf." | "aff." | "?" | "sp." | "spp." | ...
    authority: str | None = None
    rank: str | None = None
    family: str | None = None
    order: str | None = None
    class_name: str | None = None
    # Audit 2026-08-19 M-3: ``source`` now means the **taxonomic
    # data source** in the Darwin Core sense — where the family /
    # order / class_name / authority fields came from.  The legacy
    # mixed semantics (paleodb | extraction_method) was a DwC
    # ambiguity bug; the structured ``extraction_method`` field below
    # carries the pipeline-side provenance (regex | llm_first |
    # hybrid).  Valid values: ``"paleodb"`` | ``"none"`` | ``None``.
    # Kept for backwards compatibility with downstream consumers
    # that already read ``source``; new code should consult both
    # ``source`` and ``extraction_method`` separately.
    source: str | None = None
    # Audit 2026-08-19 M-3: structured pipeline-side provenance.
    # ``extraction_method`` is the same string previously embedded
    # inside ``taxon_remarks`` as ``"extraction_method=..."``.  Carrying
    # it as a structured field (rather than only in free-text remarks)
    # lets downstream consumers (GBIF, the xlsx exporter, the audit
    # dashboard) filter / group rows by extraction strategy without
    # parsing the remarks string.  Valid values mirror the pipeline:
    # ``"regex"`` | ``"llm_first"`` | ``"hybrid"`` | ``""`` (legacy
    # empty default).
    extraction_method: str | None = None
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    needs_review: bool = False
    review_reasons: list[str] = Field(default_factory=list)
    # Phase 63 Plan 6.16 (Bug 6.16): Darwin Core requires
    # ``nomenclaturalCode`` on acceptedNameUsage / recordedName
    # usages. Radiolarians are governed by ICZN
    # (International Code of Zoological Nomenclature), NOT ICN
    # (botanical). Default = "ICZN" because every record in this
    # pipeline is a fossil specimen.
    nomenclatural_code: str = "ICZN"
    # Phase 63 Plan 6.17 (Bug 6.17): ``scientificNameAuthorship``
    # carries the author/year string (``(Smith, 1900)``) extracted
    # from species strings by ``_taxon_parts`` /
    # ``_extract_authorship``. ``None`` means not in the source
    # verbatim_name.
    scientific_name_authorship: str | None = None
    # Phase 63 Plan 6.18 (Bug 6.18): ``genericName`` (DwC) for the
    # subgenus-in-parentheses shape ``Podocyrtis (Podocyrtites)``.
    # ``genus`` keeps the higher-level genus (Podocyrtis); ``genericName``
    # holds the subgenus when present (Podocyrtites).
    generic_name: str | None = None
    # Phase 63 Plan 6.19 (Bug 6.19): ``taxonRemarks`` (DwC) for
    # extraction-method / provenance notes. Round-trippable to/from
    # ``PanelRecord.metadata.extraction_method`` so reviewers can see
    # how the taxon name was determined (caption regex vs. llm-first
    # vs. hybrid).
    taxon_remarks: str | None = None
    # Audit 2026-08-02: link from TaxonRecord to one or more
    # MorphologyRecord entries extracted for the same species. Empty
    # list when Stage 6 is off, the species had no anchorable
    # description section, or M3 returned an empty dict. Stable IDs
    # (see ``converters.morphology_records_from_matches``) so the
    # JSONL export round-trips.
    morphology_ids: list[str] = Field(default_factory=list)


class SampleRecord(BaseModel):
    """A sample or specimen group mentioned in a caption or text section."""

    model_config = StrictModel
    sample_id: str
    paper_id: str
    figure_id: str | None = None
    caption_panel_range: str | None = None
    locality_id: str | None = None
    geology_context_id: str | None = None
    evidence_text: str | None = None
    page_index: int | None = None
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)


class GeologyContextRecord(BaseModel):
    """Structured geological context attached to a sample, panel, or paper."""

    model_config = StrictModel
    geology_context_id: str
    sample_id: str | None = None
    age: str | None = None
    chronostratigraphy: str | None = None
    chronostratigraphy_rank: str | None = None
    ma_top: float | None = None
    ma_base: float | None = None
    ma_mid: float | None = None
    formation: str | None = None
    member: str | None = None
    group: str | None = None
    lithology: str | None = None
    biozone: str | None = None
    locality_id: str | None = None
    evidence_text: str | None = None
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)


class MorphologyRecord(BaseModel):
    """Structured morphological description for one species.

    Audit 2026-08-02 — Stage 6 (M3 morphology extraction, opt-in).
    For each unique (paper, species) pair with an anchorable
    Description / Diagnosis section, the pipeline emits ONE
    MorphologyRecord. Fields the source text doesn't mention are
    left ``None`` — never ``False`` / ``0`` / ``""`` — so the JSONL
    export distinguishes "M3 said yes" from "M3 had nothing to
    say".
    """

    model_config = StrictModel
    morphology_id: str
    taxon_id: str
    paper_id: str
    # Provenance.
    source: str = ""  # "caption" | "body_text" | "m3_vision"
    section_id: str | None = None
    section_title: str | None = None
    figure_id: str | None = None
    panel_id: str | None = None
    page_index: int | None = None
    evidence_text: str | None = None
    # Test / overall shape.
    test_shape: str | None = None
    test_length_um_min: float | None = Field(default=None, ge=0.0)
    test_length_um_max: float | None = Field(default=None, ge=0.0)
    test_width_um_min: float | None = Field(default=None, ge=0.0)
    test_width_um_max: float | None = Field(default=None, ge=0.0)
    # Segmented-shell geometry (nassellarians).
    num_segments: int | None = Field(default=None, ge=0)
    cephalis_shape: str | None = None
    thorax_shape: str | None = None
    abdomen_shape: str | None = None
    # Pore architecture.
    pore_pattern: str | None = None
    pore_diameter_um_min: float | None = Field(default=None, ge=0.0)
    pore_diameter_um_max: float | None = Field(default=None, ge=0.0)
    # Spines.
    spines_present: bool | None = None
    spine_count: int | None = Field(default=None, ge=0)
    # Aperture.
    apertural_structure: str | None = None
    # Diagnostic / distinguishing features (verbatim short phrases).
    diagnostic_features: list[str] = Field(default_factory=list)
    # Confidence in the extraction (clamped 0..1 by the engine).
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)


class LocalityRecord(BaseModel):
    """Modern locality and optional coordinate evidence."""

    model_config = StrictModel
    locality_id: str
    # audit 2026-08-17 (EXP-1): declare paper_id so the xlsx exporter
    # (and any other consumer that round-trips via model_dump) actually
    # sees the paper the locality came from. Previously this was
    # implicit and xlsx wrote an empty "论文ID" column for every
    # locality row even when the source ``MatchResult`` clearly carried
    # ``paper_id``. ``paper_id`` is a stable identifier, so we type it
    # as ``str`` (matching PaperRecord); the converter fills it from
    # ``MatchResult.paper_id``.
    paper_id: str = ""
    name: str | None = None
    country: str | None = None
    region: str | None = None
    section_name: str | None = None
    modern_latitude: float | None = Field(default=None, ge=-90.0, le=90.0)
    modern_longitude: float | None = Field(default=None, ge=-180.0, le=180.0)
    coordinate_source: str | None = None
    geocoding_source: str | None = None
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    # Phase 63 Plan 6.15 (Bug 6.15): GBIF/PBDB requirement.
    # ``None`` when the locality has no coordinate.
    coordinate_uncertainty_in_meters: float | None = None


class PaleoCoordinateRecord(BaseModel):
    """Paleogeographic reconstruction result for one locality/time."""

    model_config = StrictModel
    paleo_coordinate_id: str
    # audit 2026-08-17 (EXP-1): see LocalityRecord.paper_id above.
    # Previously xlsx "论文ID" column was always empty for the
    # paleo_coordinates sheet even though every record came from a single
    # paper (paper_id is in scope at the call site).
    paper_id: str = ""
    locality_id: str | None = None
    modern_latitude: float | None = Field(default=None, ge=-90.0, le=90.0)
    modern_longitude: float | None = Field(default=None, ge=-180.0, le=180.0)
    reconstruction_age_ma: float | None = None
    paleo_latitude: float | None = None
    paleo_longitude: float | None = None
    plate_id: str | None = None
    reconstruction_model: str | None = None
    method: str | None = None
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    backend_status: str | None = None
    # Phase 63 Plan 6.20 (Bug 6.20): PBDB-style paleocoords carry an
    # uncertainty (typically 10-50 km for Euler-pole reconstructions).
    # ``None`` means the backend didn't report one.
    coordinate_uncertainty_in_meters: float | None = None


class WarningRecord(BaseModel):
    """A machine-readable warning/review issue emitted during extraction."""

    model_config = StrictModel
    warning_id: str
    level: str = "warning"  # "info" | "warning" | "error"
    code: str
    message: str
    entity_type: str | None = None
    entity_id: str | None = None
    evidence_text: str | None = None


class PanelMetadata(BaseModel):
    """Per-panel diagnostic metadata (no business data here)."""

    model_config = StrictModel
    panel_score: float | None = None
    ocr_count: int = 0
    taxon_count: int = 0
    figure_number: str | None = None
    page_index: int | None = None
    matcher_used: bool = False
    matcher_type: str = "heuristic"
    matcher_conf: float = 0.0
    caption_pairs_used: bool = False
    scale_bar: ScaleBarRecord | None = None
    geology_links: list[GeologyLinkRecord] = Field(default_factory=list)
    m3_diagnostic: dict[str, Any] = Field(default_factory=dict)
    # audit 2026-07-31: PBDB taxonomy forwarded from the match
    # metadata so the DwC-A exporter can populate the higher-rank
    # classification columns (kingdom … family). Optional; absent for
    # runs without use_paleodb.
    paleodb_taxonomy: dict[str, Any] | None = None
    extraction_source: str = ""
    extraction_method: str = ""
    needs_review: bool = False
    review_reasons: list[str] = Field(default_factory=list)
    reassigned_from_figure: str | None = None
    reassigned_reason: str | None = None
    # Round 18 audit: marks the SCOPE of the geology_links attached
    # to this panel. "panel" = derived from this panel's own caption;
    # "figure_anchor" = first panel inheriting the figure-level
    # caption as an anchor (others stay empty); "none" = no figure-
    # level data, so the operator sees a data gap rather than
    # fabricated per-panel data.
    geology_scope: str = ""
    # Phase 64 Plan B (Task B.2): per-panel storage for the
    # ``extract_schematic`` output on schematic / diagram /
    # reconstruction / phylogenetic figures. The shape is the same
    # JSON the M3 prompt contract emits:
    #   {
    #     "figure_type": str,
    #     "text_elements": [{text, type, confidence}, ...],
    #     "relationships": [{from, to, label}, ...],
    #     "extracted_facts": {
    #       "ages_mentioned": [...],
    #       "geographic_names": [...],
    #       "taxa_mentioned": [...],
    #     },
    #     "confidence": float,
    #   }
    # We keep the value free-form (dict[str, Any]) rather than
    # building a nested Pydantic model so the downstream export
    # path can iterate the same shape without re-marshalling.
    figure_schematic_data: dict[str, Any] | None = None
    # Phase 65 Plan A.4: cross-figure linker provenance.
    # ``link_source`` records which strategy won (``sample_match`` /
    # ``locality_match`` / ``m3_inference`` / ``unlinked``); the
    # paired ``link_confidence`` is the linker's own confidence (NOT
    # the species-extraction confidence above). ``link_figure_id``
    # is the paper-level figure id the panel was linked to (None for
    # unlinked). All three default to None / 0.0 so legacy records
    # remain valid.
    link_source: str | None = None
    link_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    link_figure_id: str | None = None
    # Phase 66 Plan C.2: VISION-coordinate cross-reference links.
    # Populated by ``link_visual_coordinates`` for panels whose
    # Phase A Strategy-1 (sample_match) didn't reach confidence 1.0
    # AND the paper has BOTH a plate figure AND a strat column /
    # paleogeographic-map figure. Each entry is a free-form dict
    # with keys:
    #   target_figure_id: str — paper-level figure id of the linked
    #                          strat column / map
    #   target_layer: int | None — 1-based strat-column layer index
    #                              (top = 1); None if not determinable
    #   target_age: str | None — chronostratigraphy string from the
    #                             linked layer
    #   target_formation: str | None — formation name on the linked
    #                                  layer
    #   confidence: float (0.0-1.0) — M3's own visual-link confidence
    #                                  (unclamped; vision grounding is
    #                                  intrinsically more reliable
    #                                  than the text-only Strategy 3)
    #   source: str — always "m3_visual" for Phase C entries
    # Default empty list so legacy Phase A records remain valid.
    cross_figure_visual_links: list[dict[str, Any]] = Field(default_factory=list)


class PanelRecord(BaseModel):
    """A single panel in a single figure of a single paper.

    This is the canonical record published as JSONL. Each downstream view
    (analysis/ML/archive) is a projection of this record.
    """

    model_config = StrictModel
    paper_id: str
    figure_id: str
    # Legacy/canonical panel id retained for backwards compatibility.
    # New product-facing exports should also fill the split id fields
    # below whenever their source is known.
    panel_id: str | None
    caption_panel_id: str | None = None
    printed_panel_id: str | None = None
    pipeline_panel_index: int | None = None
    canonical_panel_id: str | None = None
    panel_id_source: str | None = None  # "caption" | "image_ocr" | "position" | "legacy" | ...
    species: str | None
    taxon_id: str | None = None
    sample_id: str | None = None
    geology_context_id: str | None = None
    panel_path: str | None
    figure_image_path: str | None = None
    bbox: list[int] | None = Field(default=None, min_length=4, max_length=4)
    confidence: float
    label_text: str | None = None
    caption_snippet: str | None = None
    ocr_text: str | None = None
    extraction_method: str = ""
    needs_review: bool = False
    review_reasons: list[str] = Field(default_factory=list)
    # audit 2026-08-02 (Schema v1.1.0): three new optional fields
    # for downstream scientific use.
    #
    # ``confidence_interval_low`` / ``confidence_interval_high``:
    #   Wilson score 95% confidence interval for the panel-level
    #   ``confidence``. Both bounds are in [0.0, 1.0]. ``None`` when
    #   the producer did not compute a CI (e.g. heuristic-only runs).
    #
    # ``image_verified``:
    #   True once a human has looked at the panel image and confirmed
    #   the species assignment. False (the default) means the row has
    #   only been machine-extracted.
    #
    # ``review_priority``:
    #   Auto-computed priority hint for the human review queue
    #   (0 = low, 1 = medium, 2 = high). The exact scoring formula
    #   is pipeline-defined; the schema only enforces the [0, 2]
    #   range so downstream review UIs can sort on it without
    #   re-validating.
    confidence_interval_low: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Lower bound of confidence interval (Wilson score, 95%)",
    )
    confidence_interval_high: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Upper bound of confidence interval (Wilson score, 95%)",
    )
    image_verified: bool = Field(
        default=False,
        description="True if a human verified this row by looking at the panel image",
    )
    review_priority: int = Field(
        default=0,
        ge=0,
        le=2,
        description="Auto-computed review priority (0=low, 1=medium, 2=high)",
    )
    metadata: PanelMetadata = Field(default_factory=PanelMetadata)
    paper_metadata: PaperMetadataRecord | None = None


class RunOutput(BaseModel):
    """The top-level shape of an exported run.

    The provenance block is mandatory and is validated separately so a
    run without provenance cannot be exported. The panel list remains
    the backwards-compatible core view; the additional entity lists are
    optional product/data-package views built from the same extraction.
    """

    model_config = StrictModel
    schema_version: str = SCHEMA_VERSION
    provenance: ProvenanceRecord
    papers: list[PaperRecord] = Field(default_factory=list)
    figures: list[FigureRecord] = Field(default_factory=list)
    panels: list[PanelRecord] = Field(default_factory=list)
    taxa: list[TaxonRecord] = Field(default_factory=list)
    samples: list[SampleRecord] = Field(default_factory=list)
    geology_contexts: list[GeologyContextRecord] = Field(default_factory=list)
    localities: list[LocalityRecord] = Field(default_factory=list)
    paleo_coordinates: list[PaleoCoordinateRecord] = Field(default_factory=list)
    morphologies: list[MorphologyRecord] = Field(default_factory=list)
    warnings: list[WarningRecord] = Field(default_factory=list)

    @model_validator(mode="wrap")  # type: ignore[arg-type]
    def _enforce_unique_ids(
        self,
        handler: Any,
        info: Any,
    ) -> RunOutput:
        # ``handler``/``info`` are typed ``Any``: pydantic's decorator
        # overloads (``ModelWrapValidator[Never]``) reject the precise
        # ``ModelWrapValidatorHandler``/``ValidationInfo`` annotations
        # under mypy --ignore-missing-imports (invariance friction),
        # and pydantic validates the real signature at runtime.
        """Audit 2026-09-01 CR-14: enforce ID uniqueness across the
        three primary dimensions (paper_id / (paper_id, figure_id) /
        (paper_id, figure_id, panel_id)). The previous schema accepted
        silently — eval scripts that group by ``paper_id`` to compute
        F1 then double-counted the duplicated rows.

        We deduplicate *in place* on the validated object rather than
        rejecting so legacy / manually-edited gold files with
        duplicate entries still load (the duplicates are dropped
        with a WARNING — not a hard failure).

        Audit 2026-09-04 (CI regression fix): honour a
        ``context={"skip_dedup": True}`` flag passed to
        :meth:`model_validate` so the EXP-3 ``write_dwca_zip`` test
        (and any future caller that wants the raw duplicate
        ``PanelRecord`` list to flow through to the per-row dedup
        check) can opt out of the upstream :class:`RunOutput` dedup.

        Audit 2026-09-04 (second fix): the earlier rewrite of this
        method accidentally placed ``return handler(self)`` *before*
        the dedup body, making the dedup unreachable dead code for
        every caller (duplicates silently survived validation again).
        The dedup now runs after ``handler(self)`` completes the
        default validation, on the validated instance.
        """
        # mode="wrap" gives us ``info`` (with ``context`` from
        # ``model_validate(..., context={...})``) and ``handler`` to
        # invoke the default validation. When the caller opted out of
        # dedup, pass straight through.
        ctx = getattr(info, "context", {}) or {}
        if ctx.get("skip_dedup", False):
            return handler(self)

        validated = handler(self)

        import logging as _logging

        _logger = _logging.getLogger(__name__)

        def _dedup_keep_first(items: list, key_fn, label: str) -> list:
            seen: set = set()
            deduped: list = []
            for it in items:
                k = key_fn(it)
                if k in seen:
                    _logger.warning(
                        "RunOutput: dropping duplicate %s with key %r",
                        label,
                        k,
                    )
                    continue
                seen.add(k)
                deduped.append(it)
            return deduped

        # Dedup papers by paper_id.
        validated.papers = _dedup_keep_first(validated.papers, lambda p: p.paper_id, "PaperRecord")
        # Dedup figures by (paper_id, figure_id).
        validated.figures = _dedup_keep_first(
            validated.figures,
            lambda f: (f.paper_id, f.figure_id),
            "FigureRecord",
        )
        # Dedup panels by (paper_id, figure_id, panel_id).
        validated.panels = _dedup_keep_first(
            validated.panels,
            lambda p: (p.paper_id, p.figure_id, p.panel_id),
            "PanelRecord",
        )
        return validated


def emit_json_schema(target: Path) -> Path:
    """Write the canonical JSON Schema for ``RunOutput`` to ``target``.

    Idempotent: running twice with the same target produces the same file.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    schema = RunOutput.model_json_schema()
    schema["$id"] = f"https://rlpe.local/schemas/rlpe-v{SCHEMA_VERSION}.json"
    schema["title"] = "RLPE RunOutput"
    schema["description"] = (
        "Canonical export shape of a Radiolarian Literature Plate Extractor "
        "run. Each RunOutput carries a ProvenanceRecord and a list of "
        "PanelRecord entries. Downstream views (analysis/ML/archive) are "
        "projections of this shape."
    )
    # Audit 2026-09-01 CR-2 / BL-34: write atomically via temp + rename
    # so a mid-write SIGKILL never leaves a truncated JSON Schema file.
    import os as _os
    import tempfile as _tempfile

    fd, tmp_path = _tempfile.mkstemp(
        dir=str(target.parent), prefix=f".{target.name}.", suffix=".tmp"
    )
    try:
        with _os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(schema, f, indent=2, sort_keys=True, ensure_ascii=False)
            f.flush()
            try:
                _os.fsync(f.fileno())
            except OSError:
                pass
        _os.replace(tmp_path, target)
    except Exception:
        try:
            _os.unlink(tmp_path)
        except OSError:
            pass
        raise
    return target


def validate_run_output(payload: dict[str, Any]) -> RunOutput:
    """Validate a parsed JSON payload against the published schema.

    Raises ``pydantic.ValidationError`` on any mismatch. Returns the
    typed :class:`RunOutput` for downstream use.
    """
    return RunOutput.model_validate(payload, context={"skip_dedup": False})
